### ISSUE TITLE
Daily Morning Run

### ISSUE THREAD

**Issue by 444B** [444B/personal-development#11]
## Objective
**Objective:** [Briefly state the goal]
- I want to go for a run once a day to relieve stress and keep my body healthy.

## Motivation
**Why This Goal:** [Explain the motivation and importance of this goal]
- I tend to spend alot of time in front of the computer and not physically active. I wish to keep my health in the long run and also create a discipline around exercise. 

## SMART Criteria
- **Specific:** [Detail what specifically needs to be accomplished]
  - A run or a visit to the gym every day
- **Measurable:** [Define how you will measure progress and success]
  - Becoming physically stronger (being able to lift more or run farther)
- **Achievable:** [Ensure the goal is realistic and attainable]
  - This goal is realistic
- **Relevant:** [Explain how this goal aligns with broader objectives or personal aspirations]
  - Sport and excercise is proven to increase gray matter [link](https://pubmed.ncbi.nlm.nih.gov/35438607/) and to relieve stress. This will empower all my other goals and set me up for a healthy life
- **Time-bound:** [Set a deadline or timeline for achieving this goal]
  - Every day, repeats

## Context
**Context:** [Link to website or include a text box with detailed information about the goal]
- N/A

## Tasks to Completion
- [x] Get sports shoes and other equipment
- [x] Schedule time in the day to work on this : currently 1h
- [ ] Run every day until the 27th February to create a habit
- [ ] Re-evalaute goal based on new knowledge

## Dependencies
**Dependencies:** [List any dependencies or resources required]
- Running equipment
- Time
- not being sick
- 

## Challenges/Blockers
**Challenges/Blockers:** [Note any challenges or blockers faced and how they are being addressed]
- Not currently

## Review and Adjustments
**Review and Adjustments:** [Regularly review the goal and make necessary adjustments]
- None at time of Init
