### ISSUE TITLE
Side Project #1

### ISSUE THREAD

**Issue by 444B** [444B/personal-development#12]
## Objective
**Objective:** [Briefly state the goal]
- A side project to create a matching algorithm for job seekers and job providers

## Motivation
**Why This Goal:** [Explain the motivation and importance of this goal]
- The current world of job hunting tends to be very non personalized with applicants having to squish their life onto a single page and recruiters guessing whether that candidate is suitable, without knowing the full history, skills or technical implications of the applicant.

## SMART Criteria
- **Specific:** [Detail what specifically needs to be accomplished]
  - TBD
- **Measurable:** [Define how you will measure progress and success]
  - TBD
- **Achievable:** [Ensure the goal is realistic and attainable]
  - TBD
- **Relevant:** [Explain how this goal aligns with broader objectives or personal aspirations]
  - TBD
- **Time-bound:** [Set a deadline or timeline for achieving this goal]
  - TBD

## Context
**Context:** [Link to website or include a text box with detailed information about the goal]
- N/A

## Tasks to Completion
- [ ] Look into the world of job seekers and recruiters and understand the environment better
- [ ] Evaluate if this is a real issue (I am almost certain it is, at least for me)
- [ ] Create MVP
- [ ] Re-evaluate and take into account new knowledge

## Dependencies
**Dependencies:** [List any dependencies or resources required]
- Copyright and IP waivers

## Challenges/Blockers
**Challenges/Blockers:** [Note any challenges or blockers faced and how they are being addressed]
- Time to focus on this project

## Review and Adjustments
**Review and Adjustments:** [Regularly review the goal and make necessary adjustments]
- None at time of Init
