### ISSUE TITLE
Harvards CS50x

### ISSUE THREAD

**Issue by 444B** [444B/personal-development#2]
## Objective
**Objective:** [Briefly state the goal]
- My long term goal is to study computer science and achieve a degree. I want to do this from Harvards CS50 course.

## Motivation
**Why This Goal:** [Explain the motivation and importance of this goal]
- I crave the knowledge and that need can be met with studies in the mean time. My ability to study and learn about Computing is still within my grasp and I do have opportunities to deepen my knowledge.

## SMART Criteria
- **Specific:** [Detail what specifically needs to be accomplished]
  - Completing the CS50 course with a Pass
- **Measurable:** [Define how you will measure progress and success]
  - Progress will be measured by consistent progress and attending lectures
- **Achievable:** [Ensure the goal is realistic and attainable]
  - This is achievable and realistice however with all my other goals I may need to monitor my capacity to take on extra projects while working towards this long term project.
- **Relevant:** [Explain how this goal aligns with broader objectives or personal aspirations]
  - This clearly aligns with my goal of education and increasing knowledge of Computing.
- **Time-bound:** [Set a deadline or timeline for achieving this goal]
  - before 31 December 2024. 

## Context
**Context:** [Link to website or include a text box with detailed information about the goal]
- https://learning.edx.org/course/course-v1:HarvardX+CS50+X/home

## Tasks to Completion
- [x] Watch Week 0's lecture.
- [ ] Submit Problem Set 0.
- [ ] Watch Week 1's lecture.
- [ ] Optionally, watch section and shorts for Week 1.
- [ ] Submit Problem Set 1.
- [ ] Watch Week 2's lecture.
- [ ] Optionally, watch section and shorts for Week 2.
- [ ] Submit Problem Set 2.
- [ ] Watch Week 3's lecture.
- [ ] Optionally, watch section and shorts for Week 3.
- [ ] Submit Problem Set 3.
- [ ] Watch Week 4's lecture.
- [ ] Optionally, watch section and shorts for Week 4.
- [ ] Submit Problem Set 4.
- [ ] Watch Week 5's lecture.
- [ ] Optionally, watch section and shorts for Week 5.
- [ ] Submit Problem Set 5.
- [ ] Watch Week 6's lecture.
- [ ] Optionally, watch a short for Week 6.
- [ ] Submit Problem Set 6.
- [ ] Watch a special lecture on Artificial Intelligence.
- [ ] Watch Week 7's lecture.
- [ ] Optionally, watch a short for Week 7.
- [ ] Submit Problem Set 7.
- [ ] Watch Week 8's lecture.
- [ ] Optionally, watch section and shorts for Week 8.
- [ ] Submit Problem Set 8.
- [ ] Watch Week 9's lecture.
- [ ] Optionally, watch section and shorts for Week 9.
- [ ] Submit Problem Set 9.
- [ ] Watch Week 10's lecture.
- [ ] Optionally watch some Seminars.
- [ ] Submit the Final Project.

## Dependencies
**Dependencies:** [List any dependencies or resources required]
- Access to Edx
- laptop
- internet
- good time management

## Challenges/Blockers
**Challenges/Blockers:** [Note any challenges or blockers faced and how they are being addressed]
- 

## Review and Adjustments
**Review and Adjustments:** [Regularly review the goal and make necessary adjustments]
- None at time of Init
