### ISSUE TITLE
Github Foundations Certificate

### ISSUE THREAD

**Issue by 444B** [444B/personal-development#3]
## Objective
**Objective:** [Briefly state the goal]
- The goal is to study for and acquire the Github Foundations certificate with a Passing score

## Motivation
**Why This Goal:** [Explain the motivation and importance of this goal]
- As a globally ubiquitous platform for software development and open source, GitHub has become a core underpinning for many organizations and projects. It has alot of powerful features and the correct implementation of those features could mean the difference for an organization or a project. I consider myself a power user of GitHub and try to learn and make us of its various features.

## SMART Criteria
- **Specific:** [Detail what specifically needs to be accomplished]
  - A passing score on the Github Foundations exam
- **Measurable:** [Define how you will measure progress and success]
  - Progress will be measured by a completion of study material and by an increased understanding of the Github platform
- **Achievable:** [Ensure the goal is realistic and attainable]
  - This goal is achievable in the short term as I already have a decent knowledge of GitHub
- **Relevant:** [Explain how this goal aligns with broader objectives or personal aspirations]
  - This goal aligns with my broader goal of learning: skills development, software development, program management and certification. 
- **Time-bound:** [Set a deadline or timeline for achieving this goal]
  - This goal should be achieved on February 2nd 2024

## Context
**Context:** [Link to website or include a text box with detailed information about the goal]
- https://resources.github.com/learn/certifications/

## Tasks to Completion
- [x] Book Exam
- [x] [Complete Linkedin Learning Courses](https://www.linkedin.com/learning/paths/prepare-for-the-github-foundations-certification)
- [x] Take Exam at start of February
- [x] Gain passing score

## Dependencies
**Dependencies:** [List any dependencies or resources required]
- A laptop, time to study and a quite place for the exam

## Challenges/Blockers
**Challenges/Blockers:** [Note any challenges or blockers faced and how they are being addressed]
- None currently

## Review and Adjustments
**Review and Adjustments:** [Regularly review the goal and make necessary adjustments]
- None at time of Init

**Comment by 444B** [comment]
Earned a passing score today
marking as resolved
