### ISSUE TITLE
Malware Reverse Engineering

### ISSUE THREAD

**Issue by 444B** [444B/personal-development#6]
## Objective
**Objective:** [Briefly state the goal]
The Goal is to understand more about computer architecture and software development via reverse engineering. My intention for this goal are purely educational and to understand more about security related matters when it comes to programs.

## Motivation
**Why This Goal:** [Explain the motivation and importance of this goal]
My knowledge of networking is highly specialized and my other sets of knowledge are very broad. I would like to understand more about computing as it relates to the creation of software. I specifically believe that computer security is the meeting point of many aspects of Computer Science (Cryptography, networking, OS, etc..) and I think this is a great place to deepen my knowledge sets. My focus here is strictly educational and to keep myself reasonably safe while using computers.

## SMART Criteria
- **Specific:** [Detail what specifically needs to be accomplished]
  - Complete Modules in maldevacademy
- **Measurable:** [Define how you will measure progress and success]
  - The modules and other study types are able to be completed 
- **Achievable:** [Ensure the goal is realistic and attainable]
  - While the modules do exist, my foundational knowledge of C needs to improved. 
- **Relevant:** [Explain how this goal aligns with broader objectives or personal aspirations]
  - This aligns with my goals of understanding how computers operate
- **Time-bound:** [Set a deadline or timeline for achieving this goal]
  - No time limits 

## Context
**Context:** [Link to website or include a text box with detailed information about the goal]
https://maldevacademy.com/

## Tasks to Completion
- [x] Research and find courses to improve C
- [ ] Improve C knowledge [Youtube Playlist](https://www.youtube.com/playlist?list=PLvv0ScY6vfd8M-Mi_Vyrg7KgISTW3Sklt)
- [ ] Create a small project in C
- [ ] Re-evaluate if ready to begin modules
- [ ] Progress through modules

## Dependencies
**Dependencies:** [List any dependencies or resources required]
- access to maldevacademy
- laptop

## Challenges/Blockers
**Challenges/Blockers:** [Note any challenges or blockers faced and how they are being addressed]
- Time 

## Review and Adjustments
**Review and Adjustments:** [Regularly review the goal and make necessary adjustments]
- None at time of Init
