### ISSUE TITLE
Linkedinsights

### ISSUE THREAD

**Issue by 444B** [444B/personal-development#8]
## Objective
**Objective:** [Briefly state the goal]
- A way to use the Linkedin API to interact with your connections and gain insights

## Motivation
**Why This Goal:** [Explain the motivation and importance of this goal]
- As a huge social media platform with over 1B users, Linkedin is often overlooked owing to its [unhinged nature](https://reddit.com/r/linkedinlunatics/).

## SMART Criteria
- **Specific:** [Detail what specifically needs to be accomplished]
  - TBD
- **Measurable:** [Define how you will measure progress and success]
  - TBD
- **Achievable:** [Ensure the goal is realistic and attainable]
  - TBD
- **Relevant:** [Explain how this goal aligns with broader objectives or personal aspirations]
  - TBD
- **Time-bound:** [Set a deadline or timeline for achieving this goal]
  - TBD

## Context
**Context:** [Link to website or include a text box with detailed information about the goal]
- N/A

## Tasks to Completion
- [ ] Gain access to Linkedin API
- [ ] Learn how it works
- [ ] Create an MVP
- [ ] Re-evalaute based on new knowledge

## Dependencies
**Dependencies:** [List any dependencies or resources required]
- Copyright and IP Waivers

## Challenges/Blockers
**Challenges/Blockers:** [Note any challenges or blockers faced and how they are being addressed]
- Time to work on this project

## Review and Adjustments
**Review and Adjustments:** [Regularly review the goal and make necessary adjustments]
- None at time of Init
